import { WeeklyRoutine } from '../../domain/entities/WeeklyRoutine';

export const defaultRoutine: WeeklyRoutine = {
  days: [
    {
      dayNumber: 1,
      name: 'DÍA 1',
      focus: 'PUSH (Pecho, Hombro, Tríceps)',
      exercises: [
        { name: 'Press banca barra', sets: 4, reps: '6–8' },
        { name: 'Press inclinado mancuernas', sets: 4, reps: '8–10' },
        { name: 'Press plano mancuernas o máquina pecho', sets: 3, reps: '10–12' },
        { name: 'Aperturas en polea (alto → bajo)', sets: 3, reps: '12–15' },
        { name: 'Press militar barra o mancuernas', sets: 3, reps: '6–8' },
        { name: 'Extensión tríceps en polea', sets: 3, reps: '12–15' },
        { name: 'Press francés barra EZ', sets: 3, reps: '10–12' },
      ],
    },
    {
      dayNumber: 2,
      name: 'DÍA 2',
      focus: 'PULL PESADO (Espalda, Bíceps)',
      exercises: [
        { name: 'Jalón al pecho', sets: 4, reps: '6–8' },
        { name: 'Remo con barra', sets: 4, reps: '6–8' },
        { name: 'Jalón cerrado', sets: 3, reps: '10–12' },
        { name: 'Remo en polea', sets: 3, reps: '12' },
        { name: 'Face pulls', sets: 3, reps: '15–20' },
        { name: 'Curl bíceps barra', sets: 3, reps: '8–10' },
        { name: 'Curl martillo', sets: 3, reps: '12' },
        { name: 'Pullover polea (finisher)', sets: 1, reps: '20', isFinisher: true },
      ],
    },
    {
      dayNumber: 3,
      name: 'DÍA 3',
      focus: 'PIERNA (Cuádriceps dominante)',
      exercises: [
        { name: 'Sentadilla libre', sets: 4, reps: '6–8' },
        { name: 'Prensa inclinada pies bajos', sets: 4, reps: '10–12' },
        { name: 'Hack squat', sets: 3, reps: '8–10' },
        { name: 'Zancadas caminando', sets: 3, reps: '10–12 c/pierna' },
        { name: 'Extensiones + drop', sets: 3, reps: '12–15 + drop' },
        { name: 'Gemelos de pie', sets: 4, reps: '12–15' },
      ],
    },
    {
      dayNumber: 4,
      name: 'DÍA 4',
      focus: 'HOMBRO + ABDOMEN',
      exercises: [
        { name: 'Press militar', sets: 4, reps: '6–8' },
        { name: 'Elevación lateral en polea', sets: 4, reps: '12–15' },
        { name: 'Elevación lateral mancuerna', sets: 3, reps: '15–20' },
        { name: 'Reverse fly máquina/polea', sets: 3, reps: '12–15' },
        { name: 'Face pull', sets: 3, reps: '15–20' },
        { name: 'Crunch en polea', sets: 3, reps: '12–15' },
        { name: 'Elevación de piernas', sets: 3, reps: '10–15' },
        { name: 'Plancha RKC', sets: 2, reps: '20–30 seg' },
      ],
    },
    {
      dayNumber: 5,
      name: 'DÍA 5',
      focus: 'PULL METABÓLICO (Espalda + Brazos)',
      exercises: [
        { name: 'Jalón en polea agarre neutro estrecho', sets: 4, reps: '12–15' },
        { name: 'Remo en máquina pecho soportado', sets: 4, reps: '12–15' },
        { name: 'Remo en polea baja (agarre V o neutro)', sets: 3, reps: '12–15' },
        { name: 'Reverse fly en máquina o polea', sets: 3, reps: '15–20' },
        { name: 'Curl en polea de pie (tensión constante)', sets: 3, reps: '12–15' },
        { name: 'Curl inclinado mancuernas', sets: 3, reps: '12–15' },
        { name: 'Curl martillo o rope hammer', sets: 2, reps: '12–15' },
        { name: 'Face pulls moderados', sets: 2, reps: '15–20' },
      ],
    },
    {
      dayNumber: 6,
      name: 'DÍA 6',
      focus: 'PIERNA (Femoral + Glúteo)',
      exercises: [
        { name: 'Peso muerto rumano', sets: 4, reps: '6–8' },
        { name: 'Hip Thrust con barra', sets: 4, reps: '8–10' },
        { name: 'Curl femoral acostado o sentado', sets: 4, reps: '10–12' },
        { name: 'Back extension (45° o horizontal)', sets: 3, reps: '12–15' },
        { name: 'Sentadilla búlgara mancuernas', sets: 3, reps: '10–12 por pierna' },
        { name: 'Gemelo sentado o en máquina', sets: 4, reps: '12–15' },
      ],
    },
    {
      dayNumber: 7,
      name: 'DÍA 7',
      focus: 'FULL BODY METABÓLICO + CORE',
      exercises: [
        { name: 'Sentadilla Hack', sets: 3, reps: '15–20' },
        { name: 'Press inclinado mancuernas', sets: 3, reps: '12–15' },
        { name: 'Remo en polea baja', sets: 3, reps: '12–15' },
        { name: 'Elevaciones laterales', sets: 3, reps: '15–20' },
        { name: 'Curl en polea', sets: 2, reps: '12–15' },
        { name: 'Tríceps cuerda', sets: 2, reps: '12–15' },
        { name: 'Circuito: crunch + elevación piernas + plancha', sets: 3, reps: '—' },
      ],
    },
  ],
};

